version: 2.1
orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5

jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Start server
          command: npm run start
          background: true
      - run:
          name: Run Cypress tests
          command: npm run test
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main
                - staging